config/routes.rb
Ideas::Application.routes.draw do
  root :to => "ideas#index"

  match "/auth/google/callback" => "sessions#create"
  match "/sign_out" => "sessions#destroy", :as => :sign_out

  resources :ideas
end

app/models/idea.rb
class Idea < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["user_info"]["name"]
      user.email = auth["user_info"]["email"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/ideas/index.html.erb
These are the ideas:

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideas</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="user_nav">
    <% if current_user %>
      Logged in as: <%= current_user.name %>, <%= link_to "Sign out", sign_out_path %>
    <% else %>
      <%= link_to "Sign in with Google", "/auth/google" %>
    <% end %>
  </div>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>